# Site settings
title: Liam Horne
tagline: 

author:
    name: "Liam Horne"
    email: "liam@lihorne.com"
    twitter: "liamihorne"
    instagram: "snario"
    github: "snario"
    facebook: "lihorne"
    linkedin: "liamhorne"

navigation:
- title: Essays
  url: /essays
- title: Notes
  url: /notes

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lihorne.com" # the base hostname & protocol for your site

typekit_kit_id: emy7anq

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

paginate: 5

disqus_short_name: liamhorne
disqus_show_comment_count: true

google_analytics_tracking_id: UA-42840264-1
